# coding: utf-8

"""
    NetBox API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.data_67 import Data67


class TestData67(unittest.TestCase):
    """ Data67 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testData67(self):
        """
        Test Data67
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.data_67.Data67()
        pass


if __name__ == '__main__':
    unittest.main()
