# coding: utf-8

"""
    NetBox API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.data_90 import Data90


class TestData90(unittest.TestCase):
    """ Data90 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testData90(self):
        """
        Test Data90
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.data_90.Data90()
        pass


if __name__ == '__main__':
    unittest.main()
