# coding: utf-8

"""
    NetBox API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.ipam_api import IpamApi


class TestIpamApi(unittest.TestCase):
    """ IpamApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.ipam_api.IpamApi()

    def tearDown(self):
        pass

    def test_aggregates_create(self):
        """
        Test case for aggregates_create

        
        """
        pass

    def test_aggregates_delete(self):
        """
        Test case for aggregates_delete

        
        """
        pass

    def test_aggregates_list(self):
        """
        Test case for aggregates_list

        
        """
        pass

    def test_aggregates_partial_update(self):
        """
        Test case for aggregates_partial_update

        
        """
        pass

    def test_aggregates_read(self):
        """
        Test case for aggregates_read

        
        """
        pass

    def test_aggregates_update(self):
        """
        Test case for aggregates_update

        
        """
        pass

    def test_ip_addresses_create(self):
        """
        Test case for ip_addresses_create

        
        """
        pass

    def test_ip_addresses_delete(self):
        """
        Test case for ip_addresses_delete

        
        """
        pass

    def test_ip_addresses_list(self):
        """
        Test case for ip_addresses_list

        
        """
        pass

    def test_ip_addresses_partial_update(self):
        """
        Test case for ip_addresses_partial_update

        
        """
        pass

    def test_ip_addresses_read(self):
        """
        Test case for ip_addresses_read

        
        """
        pass

    def test_ip_addresses_update(self):
        """
        Test case for ip_addresses_update

        
        """
        pass

    def test_prefixes_create(self):
        """
        Test case for prefixes_create

        
        """
        pass

    def test_prefixes_delete(self):
        """
        Test case for prefixes_delete

        
        """
        pass

    def test_prefixes_list(self):
        """
        Test case for prefixes_list

        
        """
        pass

    def test_prefixes_partial_update(self):
        """
        Test case for prefixes_partial_update

        
        """
        pass

    def test_prefixes_read(self):
        """
        Test case for prefixes_read

        
        """
        pass

    def test_prefixes_update(self):
        """
        Test case for prefixes_update

        
        """
        pass

    def test_rirs_create(self):
        """
        Test case for rirs_create

        
        """
        pass

    def test_rirs_delete(self):
        """
        Test case for rirs_delete

        
        """
        pass

    def test_rirs_list(self):
        """
        Test case for rirs_list

        
        """
        pass

    def test_rirs_partial_update(self):
        """
        Test case for rirs_partial_update

        
        """
        pass

    def test_rirs_read(self):
        """
        Test case for rirs_read

        
        """
        pass

    def test_rirs_update(self):
        """
        Test case for rirs_update

        
        """
        pass

    def test_roles_create(self):
        """
        Test case for roles_create

        
        """
        pass

    def test_roles_delete(self):
        """
        Test case for roles_delete

        
        """
        pass

    def test_roles_list(self):
        """
        Test case for roles_list

        
        """
        pass

    def test_roles_partial_update(self):
        """
        Test case for roles_partial_update

        
        """
        pass

    def test_roles_read(self):
        """
        Test case for roles_read

        
        """
        pass

    def test_roles_update(self):
        """
        Test case for roles_update

        
        """
        pass

    def test_services_create(self):
        """
        Test case for services_create

        
        """
        pass

    def test_services_delete(self):
        """
        Test case for services_delete

        
        """
        pass

    def test_services_list(self):
        """
        Test case for services_list

        
        """
        pass

    def test_services_partial_update(self):
        """
        Test case for services_partial_update

        
        """
        pass

    def test_services_read(self):
        """
        Test case for services_read

        
        """
        pass

    def test_services_update(self):
        """
        Test case for services_update

        
        """
        pass

    def test_vlan_groups_create(self):
        """
        Test case for vlan_groups_create

        
        """
        pass

    def test_vlan_groups_delete(self):
        """
        Test case for vlan_groups_delete

        
        """
        pass

    def test_vlan_groups_list(self):
        """
        Test case for vlan_groups_list

        
        """
        pass

    def test_vlan_groups_partial_update(self):
        """
        Test case for vlan_groups_partial_update

        
        """
        pass

    def test_vlan_groups_read(self):
        """
        Test case for vlan_groups_read

        
        """
        pass

    def test_vlan_groups_update(self):
        """
        Test case for vlan_groups_update

        
        """
        pass

    def test_vlans_create(self):
        """
        Test case for vlans_create

        
        """
        pass

    def test_vlans_delete(self):
        """
        Test case for vlans_delete

        
        """
        pass

    def test_vlans_list(self):
        """
        Test case for vlans_list

        
        """
        pass

    def test_vlans_partial_update(self):
        """
        Test case for vlans_partial_update

        
        """
        pass

    def test_vlans_read(self):
        """
        Test case for vlans_read

        
        """
        pass

    def test_vlans_update(self):
        """
        Test case for vlans_update

        
        """
        pass

    def test_vrfs_create(self):
        """
        Test case for vrfs_create

        
        """
        pass

    def test_vrfs_delete(self):
        """
        Test case for vrfs_delete

        
        """
        pass

    def test_vrfs_list(self):
        """
        Test case for vrfs_list

        
        """
        pass

    def test_vrfs_partial_update(self):
        """
        Test case for vrfs_partial_update

        
        """
        pass

    def test_vrfs_read(self):
        """
        Test case for vrfs_read

        
        """
        pass

    def test_vrfs_update(self):
        """
        Test case for vrfs_update

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
