# coding: utf-8

"""
    NetBox API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.extras_api import ExtrasApi


class TestExtrasApi(unittest.TestCase):
    """ ExtrasApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.extras_api.ExtrasApi()

    def tearDown(self):
        pass

    def test_export_templates_create(self):
        """
        Test case for export_templates_create

        
        """
        pass

    def test_export_templates_delete(self):
        """
        Test case for export_templates_delete

        
        """
        pass

    def test_export_templates_list(self):
        """
        Test case for export_templates_list

        
        """
        pass

    def test_export_templates_partial_update(self):
        """
        Test case for export_templates_partial_update

        
        """
        pass

    def test_export_templates_read(self):
        """
        Test case for export_templates_read

        
        """
        pass

    def test_export_templates_update(self):
        """
        Test case for export_templates_update

        
        """
        pass

    def test_graphs_create(self):
        """
        Test case for graphs_create

        
        """
        pass

    def test_graphs_delete(self):
        """
        Test case for graphs_delete

        
        """
        pass

    def test_graphs_list(self):
        """
        Test case for graphs_list

        
        """
        pass

    def test_graphs_partial_update(self):
        """
        Test case for graphs_partial_update

        
        """
        pass

    def test_graphs_read(self):
        """
        Test case for graphs_read

        
        """
        pass

    def test_graphs_update(self):
        """
        Test case for graphs_update

        
        """
        pass

    def test_image_attachments_create(self):
        """
        Test case for image_attachments_create

        
        """
        pass

    def test_image_attachments_delete(self):
        """
        Test case for image_attachments_delete

        
        """
        pass

    def test_image_attachments_list(self):
        """
        Test case for image_attachments_list

        
        """
        pass

    def test_image_attachments_partial_update(self):
        """
        Test case for image_attachments_partial_update

        
        """
        pass

    def test_image_attachments_read(self):
        """
        Test case for image_attachments_read

        
        """
        pass

    def test_image_attachments_update(self):
        """
        Test case for image_attachments_update

        
        """
        pass

    def test_recent_activity_list(self):
        """
        Test case for recent_activity_list

        List all UserActions to provide a log of recent activity.
        """
        pass

    def test_recent_activity_read(self):
        """
        Test case for recent_activity_read

        List all UserActions to provide a log of recent activity.
        """
        pass

    def test_topology_maps_create(self):
        """
        Test case for topology_maps_create

        
        """
        pass

    def test_topology_maps_delete(self):
        """
        Test case for topology_maps_delete

        
        """
        pass

    def test_topology_maps_list(self):
        """
        Test case for topology_maps_list

        
        """
        pass

    def test_topology_maps_partial_update(self):
        """
        Test case for topology_maps_partial_update

        
        """
        pass

    def test_topology_maps_read(self):
        """
        Test case for topology_maps_read

        
        """
        pass

    def test_topology_maps_render(self):
        """
        Test case for topology_maps_render

        
        """
        pass

    def test_topology_maps_update(self):
        """
        Test case for topology_maps_update

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
