# coding: utf-8

"""
    NetBox API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.tenancy_api import TenancyApi


class TestTenancyApi(unittest.TestCase):
    """ TenancyApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.tenancy_api.TenancyApi()

    def tearDown(self):
        pass

    def test_tenant_groups_create(self):
        """
        Test case for tenant_groups_create

        
        """
        pass

    def test_tenant_groups_delete(self):
        """
        Test case for tenant_groups_delete

        
        """
        pass

    def test_tenant_groups_list(self):
        """
        Test case for tenant_groups_list

        
        """
        pass

    def test_tenant_groups_partial_update(self):
        """
        Test case for tenant_groups_partial_update

        
        """
        pass

    def test_tenant_groups_read(self):
        """
        Test case for tenant_groups_read

        
        """
        pass

    def test_tenant_groups_update(self):
        """
        Test case for tenant_groups_update

        
        """
        pass

    def test_tenants_create(self):
        """
        Test case for tenants_create

        
        """
        pass

    def test_tenants_delete(self):
        """
        Test case for tenants_delete

        
        """
        pass

    def test_tenants_list(self):
        """
        Test case for tenants_list

        
        """
        pass

    def test_tenants_partial_update(self):
        """
        Test case for tenants_partial_update

        
        """
        pass

    def test_tenants_read(self):
        """
        Test case for tenants_read

        
        """
        pass

    def test_tenants_update(self):
        """
        Test case for tenants_update

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
