# coding: utf-8

"""
    NetBox API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.data_52 import Data52


class TestData52(unittest.TestCase):
    """ Data52 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testData52(self):
        """
        Test Data52
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.data_52.Data52()
        pass


if __name__ == '__main__':
    unittest.main()
