# coding: utf-8

"""
    NetBox API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.data_133 import Data133


class TestData133(unittest.TestCase):
    """ Data133 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testData133(self):
        """
        Test Data133
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.data_133.Data133()
        pass


if __name__ == '__main__':
    unittest.main()
