# coding: utf-8

"""
    NetBox API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.circuits_api import CircuitsApi


class TestCircuitsApi(unittest.TestCase):
    """ CircuitsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.circuits_api.CircuitsApi()

    def tearDown(self):
        pass

    def test_circuit_terminations_create(self):
        """
        Test case for circuit_terminations_create

        
        """
        pass

    def test_circuit_terminations_delete(self):
        """
        Test case for circuit_terminations_delete

        
        """
        pass

    def test_circuit_terminations_list(self):
        """
        Test case for circuit_terminations_list

        
        """
        pass

    def test_circuit_terminations_partial_update(self):
        """
        Test case for circuit_terminations_partial_update

        
        """
        pass

    def test_circuit_terminations_read(self):
        """
        Test case for circuit_terminations_read

        
        """
        pass

    def test_circuit_terminations_update(self):
        """
        Test case for circuit_terminations_update

        
        """
        pass

    def test_circuit_types_create(self):
        """
        Test case for circuit_types_create

        
        """
        pass

    def test_circuit_types_delete(self):
        """
        Test case for circuit_types_delete

        
        """
        pass

    def test_circuit_types_list(self):
        """
        Test case for circuit_types_list

        
        """
        pass

    def test_circuit_types_partial_update(self):
        """
        Test case for circuit_types_partial_update

        
        """
        pass

    def test_circuit_types_read(self):
        """
        Test case for circuit_types_read

        
        """
        pass

    def test_circuit_types_update(self):
        """
        Test case for circuit_types_update

        
        """
        pass

    def test_circuits_create(self):
        """
        Test case for circuits_create

        
        """
        pass

    def test_circuits_delete(self):
        """
        Test case for circuits_delete

        
        """
        pass

    def test_circuits_list(self):
        """
        Test case for circuits_list

        
        """
        pass

    def test_circuits_partial_update(self):
        """
        Test case for circuits_partial_update

        
        """
        pass

    def test_circuits_read(self):
        """
        Test case for circuits_read

        
        """
        pass

    def test_circuits_update(self):
        """
        Test case for circuits_update

        
        """
        pass

    def test_providers_create(self):
        """
        Test case for providers_create

        
        """
        pass

    def test_providers_delete(self):
        """
        Test case for providers_delete

        
        """
        pass

    def test_providers_graphs(self):
        """
        Test case for providers_graphs

        A convenience method for rendering graphs for a particular provider.
        """
        pass

    def test_providers_list(self):
        """
        Test case for providers_list

        
        """
        pass

    def test_providers_partial_update(self):
        """
        Test case for providers_partial_update

        
        """
        pass

    def test_providers_read(self):
        """
        Test case for providers_read

        
        """
        pass

    def test_providers_update(self):
        """
        Test case for providers_update

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
