# coding: utf-8

"""
    NetBox API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.dcim_api import DcimApi


class TestDcimApi(unittest.TestCase):
    """ DcimApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.dcim_api.DcimApi()

    def tearDown(self):
        pass

    def test_connected_device_list(self):
        """
        Test case for connected_device_list

        This endpoint allows a user to determine what device (if any) is connected to a given peer device and peer
        """
        pass

    def test_console_connections_list(self):
        """
        Test case for console_connections_list

        
        """
        pass

    def test_console_port_templates_create(self):
        """
        Test case for console_port_templates_create

        
        """
        pass

    def test_console_port_templates_delete(self):
        """
        Test case for console_port_templates_delete

        
        """
        pass

    def test_console_port_templates_list(self):
        """
        Test case for console_port_templates_list

        
        """
        pass

    def test_console_port_templates_partial_update(self):
        """
        Test case for console_port_templates_partial_update

        
        """
        pass

    def test_console_port_templates_read(self):
        """
        Test case for console_port_templates_read

        
        """
        pass

    def test_console_port_templates_update(self):
        """
        Test case for console_port_templates_update

        
        """
        pass

    def test_console_ports_create(self):
        """
        Test case for console_ports_create

        
        """
        pass

    def test_console_ports_delete(self):
        """
        Test case for console_ports_delete

        
        """
        pass

    def test_console_ports_list(self):
        """
        Test case for console_ports_list

        
        """
        pass

    def test_console_ports_partial_update(self):
        """
        Test case for console_ports_partial_update

        
        """
        pass

    def test_console_ports_read(self):
        """
        Test case for console_ports_read

        
        """
        pass

    def test_console_ports_update(self):
        """
        Test case for console_ports_update

        
        """
        pass

    def test_console_server_port_templates_create(self):
        """
        Test case for console_server_port_templates_create

        
        """
        pass

    def test_console_server_port_templates_delete(self):
        """
        Test case for console_server_port_templates_delete

        
        """
        pass

    def test_console_server_port_templates_list(self):
        """
        Test case for console_server_port_templates_list

        
        """
        pass

    def test_console_server_port_templates_partial_update(self):
        """
        Test case for console_server_port_templates_partial_update

        
        """
        pass

    def test_console_server_port_templates_read(self):
        """
        Test case for console_server_port_templates_read

        
        """
        pass

    def test_console_server_port_templates_update(self):
        """
        Test case for console_server_port_templates_update

        
        """
        pass

    def test_console_server_ports_create(self):
        """
        Test case for console_server_ports_create

        
        """
        pass

    def test_console_server_ports_delete(self):
        """
        Test case for console_server_ports_delete

        
        """
        pass

    def test_console_server_ports_list(self):
        """
        Test case for console_server_ports_list

        
        """
        pass

    def test_console_server_ports_partial_update(self):
        """
        Test case for console_server_ports_partial_update

        
        """
        pass

    def test_console_server_ports_read(self):
        """
        Test case for console_server_ports_read

        
        """
        pass

    def test_console_server_ports_update(self):
        """
        Test case for console_server_ports_update

        
        """
        pass

    def test_device_bay_templates_create(self):
        """
        Test case for device_bay_templates_create

        
        """
        pass

    def test_device_bay_templates_delete(self):
        """
        Test case for device_bay_templates_delete

        
        """
        pass

    def test_device_bay_templates_list(self):
        """
        Test case for device_bay_templates_list

        
        """
        pass

    def test_device_bay_templates_partial_update(self):
        """
        Test case for device_bay_templates_partial_update

        
        """
        pass

    def test_device_bay_templates_read(self):
        """
        Test case for device_bay_templates_read

        
        """
        pass

    def test_device_bay_templates_update(self):
        """
        Test case for device_bay_templates_update

        
        """
        pass

    def test_device_bays_create(self):
        """
        Test case for device_bays_create

        
        """
        pass

    def test_device_bays_delete(self):
        """
        Test case for device_bays_delete

        
        """
        pass

    def test_device_bays_list(self):
        """
        Test case for device_bays_list

        
        """
        pass

    def test_device_bays_partial_update(self):
        """
        Test case for device_bays_partial_update

        
        """
        pass

    def test_device_bays_read(self):
        """
        Test case for device_bays_read

        
        """
        pass

    def test_device_bays_update(self):
        """
        Test case for device_bays_update

        
        """
        pass

    def test_device_roles_create(self):
        """
        Test case for device_roles_create

        
        """
        pass

    def test_device_roles_delete(self):
        """
        Test case for device_roles_delete

        
        """
        pass

    def test_device_roles_list(self):
        """
        Test case for device_roles_list

        
        """
        pass

    def test_device_roles_partial_update(self):
        """
        Test case for device_roles_partial_update

        
        """
        pass

    def test_device_roles_read(self):
        """
        Test case for device_roles_read

        
        """
        pass

    def test_device_roles_update(self):
        """
        Test case for device_roles_update

        
        """
        pass

    def test_device_types_create(self):
        """
        Test case for device_types_create

        
        """
        pass

    def test_device_types_delete(self):
        """
        Test case for device_types_delete

        
        """
        pass

    def test_device_types_list(self):
        """
        Test case for device_types_list

        
        """
        pass

    def test_device_types_partial_update(self):
        """
        Test case for device_types_partial_update

        
        """
        pass

    def test_device_types_read(self):
        """
        Test case for device_types_read

        
        """
        pass

    def test_device_types_update(self):
        """
        Test case for device_types_update

        
        """
        pass

    def test_devices_create(self):
        """
        Test case for devices_create

        
        """
        pass

    def test_devices_delete(self):
        """
        Test case for devices_delete

        
        """
        pass

    def test_devices_list(self):
        """
        Test case for devices_list

        
        """
        pass

    def test_devices_lldp_neighbors(self):
        """
        Test case for devices_lldp_neighbors

        Retrieve live LLDP neighbors of a device
        """
        pass

    def test_devices_partial_update(self):
        """
        Test case for devices_partial_update

        
        """
        pass

    def test_devices_read(self):
        """
        Test case for devices_read

        
        """
        pass

    def test_devices_update(self):
        """
        Test case for devices_update

        
        """
        pass

    def test_interface_connections_create(self):
        """
        Test case for interface_connections_create

        
        """
        pass

    def test_interface_connections_delete(self):
        """
        Test case for interface_connections_delete

        
        """
        pass

    def test_interface_connections_list(self):
        """
        Test case for interface_connections_list

        
        """
        pass

    def test_interface_connections_partial_update(self):
        """
        Test case for interface_connections_partial_update

        
        """
        pass

    def test_interface_connections_read(self):
        """
        Test case for interface_connections_read

        
        """
        pass

    def test_interface_connections_update(self):
        """
        Test case for interface_connections_update

        
        """
        pass

    def test_interface_templates_create(self):
        """
        Test case for interface_templates_create

        
        """
        pass

    def test_interface_templates_delete(self):
        """
        Test case for interface_templates_delete

        
        """
        pass

    def test_interface_templates_list(self):
        """
        Test case for interface_templates_list

        
        """
        pass

    def test_interface_templates_partial_update(self):
        """
        Test case for interface_templates_partial_update

        
        """
        pass

    def test_interface_templates_read(self):
        """
        Test case for interface_templates_read

        
        """
        pass

    def test_interface_templates_update(self):
        """
        Test case for interface_templates_update

        
        """
        pass

    def test_interfaces_create(self):
        """
        Test case for interfaces_create

        
        """
        pass

    def test_interfaces_delete(self):
        """
        Test case for interfaces_delete

        
        """
        pass

    def test_interfaces_graphs(self):
        """
        Test case for interfaces_graphs

        A convenience method for rendering graphs for a particular interface.
        """
        pass

    def test_interfaces_list(self):
        """
        Test case for interfaces_list

        
        """
        pass

    def test_interfaces_partial_update(self):
        """
        Test case for interfaces_partial_update

        
        """
        pass

    def test_interfaces_read(self):
        """
        Test case for interfaces_read

        
        """
        pass

    def test_interfaces_update(self):
        """
        Test case for interfaces_update

        
        """
        pass

    def test_inventory_items_create(self):
        """
        Test case for inventory_items_create

        
        """
        pass

    def test_inventory_items_delete(self):
        """
        Test case for inventory_items_delete

        
        """
        pass

    def test_inventory_items_list(self):
        """
        Test case for inventory_items_list

        
        """
        pass

    def test_inventory_items_partial_update(self):
        """
        Test case for inventory_items_partial_update

        
        """
        pass

    def test_inventory_items_read(self):
        """
        Test case for inventory_items_read

        
        """
        pass

    def test_inventory_items_update(self):
        """
        Test case for inventory_items_update

        
        """
        pass

    def test_manufacturers_create(self):
        """
        Test case for manufacturers_create

        
        """
        pass

    def test_manufacturers_delete(self):
        """
        Test case for manufacturers_delete

        
        """
        pass

    def test_manufacturers_list(self):
        """
        Test case for manufacturers_list

        
        """
        pass

    def test_manufacturers_partial_update(self):
        """
        Test case for manufacturers_partial_update

        
        """
        pass

    def test_manufacturers_read(self):
        """
        Test case for manufacturers_read

        
        """
        pass

    def test_manufacturers_update(self):
        """
        Test case for manufacturers_update

        
        """
        pass

    def test_platforms_create(self):
        """
        Test case for platforms_create

        
        """
        pass

    def test_platforms_delete(self):
        """
        Test case for platforms_delete

        
        """
        pass

    def test_platforms_list(self):
        """
        Test case for platforms_list

        
        """
        pass

    def test_platforms_partial_update(self):
        """
        Test case for platforms_partial_update

        
        """
        pass

    def test_platforms_read(self):
        """
        Test case for platforms_read

        
        """
        pass

    def test_platforms_update(self):
        """
        Test case for platforms_update

        
        """
        pass

    def test_power_connections_list(self):
        """
        Test case for power_connections_list

        
        """
        pass

    def test_power_outlet_templates_create(self):
        """
        Test case for power_outlet_templates_create

        
        """
        pass

    def test_power_outlet_templates_delete(self):
        """
        Test case for power_outlet_templates_delete

        
        """
        pass

    def test_power_outlet_templates_list(self):
        """
        Test case for power_outlet_templates_list

        
        """
        pass

    def test_power_outlet_templates_partial_update(self):
        """
        Test case for power_outlet_templates_partial_update

        
        """
        pass

    def test_power_outlet_templates_read(self):
        """
        Test case for power_outlet_templates_read

        
        """
        pass

    def test_power_outlet_templates_update(self):
        """
        Test case for power_outlet_templates_update

        
        """
        pass

    def test_power_outlets_create(self):
        """
        Test case for power_outlets_create

        
        """
        pass

    def test_power_outlets_delete(self):
        """
        Test case for power_outlets_delete

        
        """
        pass

    def test_power_outlets_list(self):
        """
        Test case for power_outlets_list

        
        """
        pass

    def test_power_outlets_partial_update(self):
        """
        Test case for power_outlets_partial_update

        
        """
        pass

    def test_power_outlets_read(self):
        """
        Test case for power_outlets_read

        
        """
        pass

    def test_power_outlets_update(self):
        """
        Test case for power_outlets_update

        
        """
        pass

    def test_power_port_templates_create(self):
        """
        Test case for power_port_templates_create

        
        """
        pass

    def test_power_port_templates_delete(self):
        """
        Test case for power_port_templates_delete

        
        """
        pass

    def test_power_port_templates_list(self):
        """
        Test case for power_port_templates_list

        
        """
        pass

    def test_power_port_templates_partial_update(self):
        """
        Test case for power_port_templates_partial_update

        
        """
        pass

    def test_power_port_templates_read(self):
        """
        Test case for power_port_templates_read

        
        """
        pass

    def test_power_port_templates_update(self):
        """
        Test case for power_port_templates_update

        
        """
        pass

    def test_power_ports_create(self):
        """
        Test case for power_ports_create

        
        """
        pass

    def test_power_ports_delete(self):
        """
        Test case for power_ports_delete

        
        """
        pass

    def test_power_ports_list(self):
        """
        Test case for power_ports_list

        
        """
        pass

    def test_power_ports_partial_update(self):
        """
        Test case for power_ports_partial_update

        
        """
        pass

    def test_power_ports_read(self):
        """
        Test case for power_ports_read

        
        """
        pass

    def test_power_ports_update(self):
        """
        Test case for power_ports_update

        
        """
        pass

    def test_rack_groups_create(self):
        """
        Test case for rack_groups_create

        
        """
        pass

    def test_rack_groups_delete(self):
        """
        Test case for rack_groups_delete

        
        """
        pass

    def test_rack_groups_list(self):
        """
        Test case for rack_groups_list

        
        """
        pass

    def test_rack_groups_partial_update(self):
        """
        Test case for rack_groups_partial_update

        
        """
        pass

    def test_rack_groups_read(self):
        """
        Test case for rack_groups_read

        
        """
        pass

    def test_rack_groups_update(self):
        """
        Test case for rack_groups_update

        
        """
        pass

    def test_rack_reservations_create(self):
        """
        Test case for rack_reservations_create

        
        """
        pass

    def test_rack_reservations_delete(self):
        """
        Test case for rack_reservations_delete

        
        """
        pass

    def test_rack_reservations_list(self):
        """
        Test case for rack_reservations_list

        
        """
        pass

    def test_rack_reservations_partial_update(self):
        """
        Test case for rack_reservations_partial_update

        
        """
        pass

    def test_rack_reservations_read(self):
        """
        Test case for rack_reservations_read

        
        """
        pass

    def test_rack_reservations_update(self):
        """
        Test case for rack_reservations_update

        
        """
        pass

    def test_rack_roles_create(self):
        """
        Test case for rack_roles_create

        
        """
        pass

    def test_rack_roles_delete(self):
        """
        Test case for rack_roles_delete

        
        """
        pass

    def test_rack_roles_list(self):
        """
        Test case for rack_roles_list

        
        """
        pass

    def test_rack_roles_partial_update(self):
        """
        Test case for rack_roles_partial_update

        
        """
        pass

    def test_rack_roles_read(self):
        """
        Test case for rack_roles_read

        
        """
        pass

    def test_rack_roles_update(self):
        """
        Test case for rack_roles_update

        
        """
        pass

    def test_racks_create(self):
        """
        Test case for racks_create

        
        """
        pass

    def test_racks_delete(self):
        """
        Test case for racks_delete

        
        """
        pass

    def test_racks_list(self):
        """
        Test case for racks_list

        
        """
        pass

    def test_racks_partial_update(self):
        """
        Test case for racks_partial_update

        
        """
        pass

    def test_racks_read(self):
        """
        Test case for racks_read

        
        """
        pass

    def test_racks_units(self):
        """
        Test case for racks_units

        List rack units (by rack)
        """
        pass

    def test_racks_update(self):
        """
        Test case for racks_update

        
        """
        pass

    def test_regions_create(self):
        """
        Test case for regions_create

        
        """
        pass

    def test_regions_delete(self):
        """
        Test case for regions_delete

        
        """
        pass

    def test_regions_list(self):
        """
        Test case for regions_list

        
        """
        pass

    def test_regions_partial_update(self):
        """
        Test case for regions_partial_update

        
        """
        pass

    def test_regions_read(self):
        """
        Test case for regions_read

        
        """
        pass

    def test_regions_update(self):
        """
        Test case for regions_update

        
        """
        pass

    def test_sites_create(self):
        """
        Test case for sites_create

        
        """
        pass

    def test_sites_delete(self):
        """
        Test case for sites_delete

        
        """
        pass

    def test_sites_graphs(self):
        """
        Test case for sites_graphs

        A convenience method for rendering graphs for a particular site.
        """
        pass

    def test_sites_list(self):
        """
        Test case for sites_list

        
        """
        pass

    def test_sites_partial_update(self):
        """
        Test case for sites_partial_update

        
        """
        pass

    def test_sites_read(self):
        """
        Test case for sites_read

        
        """
        pass

    def test_sites_update(self):
        """
        Test case for sites_update

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
