# coding: utf-8

"""
    NetBox API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Data78(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'u_height': 'int',
        'group': 'str',
        'name': 'str',
        'site': 'str',
        'comments': 'str',
        'custom_fields': 'str',
        'width': 'str',
        'facility_id': 'str',
        'role': 'str',
        'desc_units': 'bool',
        'type': 'str',
        'tenant': 'str'
    }

    attribute_map = {
        'u_height': 'u_height',
        'group': 'group',
        'name': 'name',
        'site': 'site',
        'comments': 'comments',
        'custom_fields': 'custom_fields',
        'width': 'width',
        'facility_id': 'facility_id',
        'role': 'role',
        'desc_units': 'desc_units',
        'type': 'type',
        'tenant': 'tenant'
    }

    def __init__(self, u_height=None, group=None, name=None, site=None, comments=None, custom_fields=None, width=None, facility_id=None, role=None, desc_units=None, type=None, tenant=None):
        """
        Data78 - a model defined in Swagger
        """

        self._u_height = None
        self._group = None
        self._name = None
        self._site = None
        self._comments = None
        self._custom_fields = None
        self._width = None
        self._facility_id = None
        self._role = None
        self._desc_units = None
        self._type = None
        self._tenant = None

        if u_height is not None:
          self.u_height = u_height
        if group is not None:
          self.group = group
        self.name = name
        self.site = site
        if comments is not None:
          self.comments = comments
        if custom_fields is not None:
          self.custom_fields = custom_fields
        if width is not None:
          self.width = width
        if facility_id is not None:
          self.facility_id = facility_id
        if role is not None:
          self.role = role
        if desc_units is not None:
          self.desc_units = desc_units
        if type is not None:
          self.type = type
        if tenant is not None:
          self.tenant = tenant

    @property
    def u_height(self):
        """
        Gets the u_height of this Data78.
        

        :return: The u_height of this Data78.
        :rtype: int
        """
        return self._u_height

    @u_height.setter
    def u_height(self, u_height):
        """
        Sets the u_height of this Data78.
        

        :param u_height: The u_height of this Data78.
        :type: int
        """

        self._u_height = u_height

    @property
    def group(self):
        """
        Gets the group of this Data78.
        

        :return: The group of this Data78.
        :rtype: str
        """
        return self._group

    @group.setter
    def group(self, group):
        """
        Sets the group of this Data78.
        

        :param group: The group of this Data78.
        :type: str
        """

        self._group = group

    @property
    def name(self):
        """
        Gets the name of this Data78.
        

        :return: The name of this Data78.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Data78.
        

        :param name: The name of this Data78.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def site(self):
        """
        Gets the site of this Data78.
        

        :return: The site of this Data78.
        :rtype: str
        """
        return self._site

    @site.setter
    def site(self, site):
        """
        Sets the site of this Data78.
        

        :param site: The site of this Data78.
        :type: str
        """
        if site is None:
            raise ValueError("Invalid value for `site`, must not be `None`")

        self._site = site

    @property
    def comments(self):
        """
        Gets the comments of this Data78.
        

        :return: The comments of this Data78.
        :rtype: str
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """
        Sets the comments of this Data78.
        

        :param comments: The comments of this Data78.
        :type: str
        """

        self._comments = comments

    @property
    def custom_fields(self):
        """
        Gets the custom_fields of this Data78.
        

        :return: The custom_fields of this Data78.
        :rtype: str
        """
        return self._custom_fields

    @custom_fields.setter
    def custom_fields(self, custom_fields):
        """
        Sets the custom_fields of this Data78.
        

        :param custom_fields: The custom_fields of this Data78.
        :type: str
        """

        self._custom_fields = custom_fields

    @property
    def width(self):
        """
        Gets the width of this Data78.
        Rail-to-rail width

        :return: The width of this Data78.
        :rtype: str
        """
        return self._width

    @width.setter
    def width(self, width):
        """
        Sets the width of this Data78.
        Rail-to-rail width

        :param width: The width of this Data78.
        :type: str
        """

        self._width = width

    @property
    def facility_id(self):
        """
        Gets the facility_id of this Data78.
        

        :return: The facility_id of this Data78.
        :rtype: str
        """
        return self._facility_id

    @facility_id.setter
    def facility_id(self, facility_id):
        """
        Sets the facility_id of this Data78.
        

        :param facility_id: The facility_id of this Data78.
        :type: str
        """

        self._facility_id = facility_id

    @property
    def role(self):
        """
        Gets the role of this Data78.
        

        :return: The role of this Data78.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """
        Sets the role of this Data78.
        

        :param role: The role of this Data78.
        :type: str
        """

        self._role = role

    @property
    def desc_units(self):
        """
        Gets the desc_units of this Data78.
        Units are numbered top-to-bottom

        :return: The desc_units of this Data78.
        :rtype: bool
        """
        return self._desc_units

    @desc_units.setter
    def desc_units(self, desc_units):
        """
        Sets the desc_units of this Data78.
        Units are numbered top-to-bottom

        :param desc_units: The desc_units of this Data78.
        :type: bool
        """

        self._desc_units = desc_units

    @property
    def type(self):
        """
        Gets the type of this Data78.
        

        :return: The type of this Data78.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Data78.
        

        :param type: The type of this Data78.
        :type: str
        """

        self._type = type

    @property
    def tenant(self):
        """
        Gets the tenant of this Data78.
        

        :return: The tenant of this Data78.
        :rtype: str
        """
        return self._tenant

    @tenant.setter
    def tenant(self, tenant):
        """
        Sets the tenant of this Data78.
        

        :param tenant: The tenant of this Data78.
        :type: str
        """

        self._tenant = tenant

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Data78):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
