# coding: utf-8

"""
    NetBox API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Data92(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'link': 'str',
        'source': 'str',
        'type': 'str',
        'name': 'str',
        'weight': 'int'
    }

    attribute_map = {
        'link': 'link',
        'source': 'source',
        'type': 'type',
        'name': 'name',
        'weight': 'weight'
    }

    def __init__(self, link=None, source=None, type=None, name=None, weight=None):
        """
        Data92 - a model defined in Swagger
        """

        self._link = None
        self._source = None
        self._type = None
        self._name = None
        self._weight = None

        if link is not None:
          self.link = link
        if source is not None:
          self.source = source
        if type is not None:
          self.type = type
        if name is not None:
          self.name = name
        if weight is not None:
          self.weight = weight

    @property
    def link(self):
        """
        Gets the link of this Data92.
        

        :return: The link of this Data92.
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link):
        """
        Sets the link of this Data92.
        

        :param link: The link of this Data92.
        :type: str
        """

        self._link = link

    @property
    def source(self):
        """
        Gets the source of this Data92.
        

        :return: The source of this Data92.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """
        Sets the source of this Data92.
        

        :param source: The source of this Data92.
        :type: str
        """

        self._source = source

    @property
    def type(self):
        """
        Gets the type of this Data92.
        

        :return: The type of this Data92.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Data92.
        

        :param type: The type of this Data92.
        :type: str
        """

        self._type = type

    @property
    def name(self):
        """
        Gets the name of this Data92.
        

        :return: The name of this Data92.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Data92.
        

        :param name: The name of this Data92.
        :type: str
        """

        self._name = name

    @property
    def weight(self):
        """
        Gets the weight of this Data92.
        

        :return: The weight of this Data92.
        :rtype: int
        """
        return self._weight

    @weight.setter
    def weight(self, weight):
        """
        Sets the weight of this Data92.
        

        :param weight: The weight of this Data92.
        :type: int
        """

        self._weight = weight

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Data92):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
