# coding: utf-8

"""
    NetBox API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Data131(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'device': 'str',
        'plaintext': 'str',
        'role': 'str',
        'name': 'str'
    }

    attribute_map = {
        'device': 'device',
        'plaintext': 'plaintext',
        'role': 'role',
        'name': 'name'
    }

    def __init__(self, device=None, plaintext=None, role=None, name=None):
        """
        Data131 - a model defined in Swagger
        """

        self._device = None
        self._plaintext = None
        self._role = None
        self._name = None

        if device is not None:
          self.device = device
        if plaintext is not None:
          self.plaintext = plaintext
        if role is not None:
          self.role = role
        if name is not None:
          self.name = name

    @property
    def device(self):
        """
        Gets the device of this Data131.
        

        :return: The device of this Data131.
        :rtype: str
        """
        return self._device

    @device.setter
    def device(self, device):
        """
        Sets the device of this Data131.
        

        :param device: The device of this Data131.
        :type: str
        """

        self._device = device

    @property
    def plaintext(self):
        """
        Gets the plaintext of this Data131.
        

        :return: The plaintext of this Data131.
        :rtype: str
        """
        return self._plaintext

    @plaintext.setter
    def plaintext(self, plaintext):
        """
        Sets the plaintext of this Data131.
        

        :param plaintext: The plaintext of this Data131.
        :type: str
        """

        self._plaintext = plaintext

    @property
    def role(self):
        """
        Gets the role of this Data131.
        

        :return: The role of this Data131.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """
        Sets the role of this Data131.
        

        :param role: The role of this Data131.
        :type: str
        """

        self._role = role

    @property
    def name(self):
        """
        Gets the name of this Data131.
        

        :return: The name of this Data131.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Data131.
        

        :param name: The name of this Data131.
        :type: str
        """

        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Data131):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
