# coding: utf-8

"""
    NetBox API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Data87(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'template_code': 'str',
        'file_extension': 'str',
        'content_type': 'str',
        'mime_type': 'str',
        'description': 'str'
    }

    attribute_map = {
        'name': 'name',
        'template_code': 'template_code',
        'file_extension': 'file_extension',
        'content_type': 'content_type',
        'mime_type': 'mime_type',
        'description': 'description'
    }

    def __init__(self, name=None, template_code=None, file_extension=None, content_type=None, mime_type=None, description=None):
        """
        Data87 - a model defined in Swagger
        """

        self._name = None
        self._template_code = None
        self._file_extension = None
        self._content_type = None
        self._mime_type = None
        self._description = None

        self.name = name
        self.template_code = template_code
        if file_extension is not None:
          self.file_extension = file_extension
        self.content_type = content_type
        if mime_type is not None:
          self.mime_type = mime_type
        if description is not None:
          self.description = description

    @property
    def name(self):
        """
        Gets the name of this Data87.
        

        :return: The name of this Data87.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Data87.
        

        :param name: The name of this Data87.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def template_code(self):
        """
        Gets the template_code of this Data87.
        

        :return: The template_code of this Data87.
        :rtype: str
        """
        return self._template_code

    @template_code.setter
    def template_code(self, template_code):
        """
        Sets the template_code of this Data87.
        

        :param template_code: The template_code of this Data87.
        :type: str
        """
        if template_code is None:
            raise ValueError("Invalid value for `template_code`, must not be `None`")

        self._template_code = template_code

    @property
    def file_extension(self):
        """
        Gets the file_extension of this Data87.
        

        :return: The file_extension of this Data87.
        :rtype: str
        """
        return self._file_extension

    @file_extension.setter
    def file_extension(self, file_extension):
        """
        Sets the file_extension of this Data87.
        

        :param file_extension: The file_extension of this Data87.
        :type: str
        """

        self._file_extension = file_extension

    @property
    def content_type(self):
        """
        Gets the content_type of this Data87.
        

        :return: The content_type of this Data87.
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """
        Sets the content_type of this Data87.
        

        :param content_type: The content_type of this Data87.
        :type: str
        """
        if content_type is None:
            raise ValueError("Invalid value for `content_type`, must not be `None`")

        self._content_type = content_type

    @property
    def mime_type(self):
        """
        Gets the mime_type of this Data87.
        

        :return: The mime_type of this Data87.
        :rtype: str
        """
        return self._mime_type

    @mime_type.setter
    def mime_type(self, mime_type):
        """
        Sets the mime_type of this Data87.
        

        :param mime_type: The mime_type of this Data87.
        :type: str
        """

        self._mime_type = mime_type

    @property
    def description(self):
        """
        Gets the description of this Data87.
        

        :return: The description of this Data87.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this Data87.
        

        :param description: The description of this Data87.
        :type: str
        """

        self._description = description

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Data87):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
