# coding: utf-8

"""
    NetBox API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Data73(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'units': 'str',
        'rack': 'str',
        'description': 'str'
    }

    attribute_map = {
        'units': 'units',
        'rack': 'rack',
        'description': 'description'
    }

    def __init__(self, units=None, rack=None, description=None):
        """
        Data73 - a model defined in Swagger
        """

        self._units = None
        self._rack = None
        self._description = None

        self.units = units
        self.rack = rack
        self.description = description

    @property
    def units(self):
        """
        Gets the units of this Data73.
        

        :return: The units of this Data73.
        :rtype: str
        """
        return self._units

    @units.setter
    def units(self, units):
        """
        Sets the units of this Data73.
        

        :param units: The units of this Data73.
        :type: str
        """
        if units is None:
            raise ValueError("Invalid value for `units`, must not be `None`")

        self._units = units

    @property
    def rack(self):
        """
        Gets the rack of this Data73.
        

        :return: The rack of this Data73.
        :rtype: str
        """
        return self._rack

    @rack.setter
    def rack(self, rack):
        """
        Sets the rack of this Data73.
        

        :param rack: The rack of this Data73.
        :type: str
        """
        if rack is None:
            raise ValueError("Invalid value for `rack`, must not be `None`")

        self._rack = rack

    @property
    def description(self):
        """
        Gets the description of this Data73.
        

        :return: The description of this Data73.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this Data73.
        

        :param description: The description of this Data73.
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")

        self._description = description

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Data73):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
