# coding: utf-8

"""
    NetBox API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Data40(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'connection_status': 'str',
        'interface_b': 'str',
        'interface_a': 'str'
    }

    attribute_map = {
        'connection_status': 'connection_status',
        'interface_b': 'interface_b',
        'interface_a': 'interface_a'
    }

    def __init__(self, connection_status=None, interface_b=None, interface_a=None):
        """
        Data40 - a model defined in Swagger
        """

        self._connection_status = None
        self._interface_b = None
        self._interface_a = None

        if connection_status is not None:
          self.connection_status = connection_status
        self.interface_b = interface_b
        self.interface_a = interface_a

    @property
    def connection_status(self):
        """
        Gets the connection_status of this Data40.
        

        :return: The connection_status of this Data40.
        :rtype: str
        """
        return self._connection_status

    @connection_status.setter
    def connection_status(self, connection_status):
        """
        Sets the connection_status of this Data40.
        

        :param connection_status: The connection_status of this Data40.
        :type: str
        """

        self._connection_status = connection_status

    @property
    def interface_b(self):
        """
        Gets the interface_b of this Data40.
        

        :return: The interface_b of this Data40.
        :rtype: str
        """
        return self._interface_b

    @interface_b.setter
    def interface_b(self, interface_b):
        """
        Sets the interface_b of this Data40.
        

        :param interface_b: The interface_b of this Data40.
        :type: str
        """
        if interface_b is None:
            raise ValueError("Invalid value for `interface_b`, must not be `None`")

        self._interface_b = interface_b

    @property
    def interface_a(self):
        """
        Gets the interface_a of this Data40.
        

        :return: The interface_a of this Data40.
        :rtype: str
        """
        return self._interface_a

    @interface_a.setter
    def interface_a(self, interface_a):
        """
        Sets the interface_a of this Data40.
        

        :param interface_a: The interface_a of this Data40.
        :type: str
        """
        if interface_a is None:
            raise ValueError("Invalid value for `interface_a`, must not be `None`")

        self._interface_a = interface_a

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Data40):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
